### ISSUE TITLE
Failed Installation

### ISSUE THREAD

**Issue by go4cas** [expandjs/expandjs-starter-kit#1]
Can you please add documentation on how to use this sample app?

I have done the following

1. Cloned the repo
2. `npm install`
3. `bower install`

The `bower install` fails with the following error: `Failed to execute "git ls-remote --tags --heads git://github.com/ExpandJS/app-elements.git", exit code of #128 fatal: remote error:    Repository not found.`

Then when running the build with `npm run build`, it fails - I assume this is related to the bower dependencies not being installed correctly?

The `package.json` is also missing the `ejs` dependency.

**Comment by Pupix** [comment]
Hello! We've fixed it. Just download the latest version and you should be all good.
